### ISSUE TITLE
Quick question on testing

### ISSUE THREAD

**Issue by sameera207** [rubyperu/ready4rails#13]
Hey @Florent2, thanks for the great project ! :+1:  . I would also like to contribute as and when time permits. 

I would like to start with adding some more tests around the code. Before starting I have a quick question. I can see the project is using the standard rails test framework, so have you decided to stick with it or is there flexibility to move to `rspec` ?

I'm more comfortable with `rspec` and if you are ok, I would rewrite the current tests and add some more with `rspec` and `factory girl`

let me know your thoughts

cheers
Sam

**Comment by Florent2** [comment]
hi @sameera207 more tests would be great, any contribution is welcome, and no problem with using `rspec` and `factory_girl`, thanks!

**Comment by sameera207** [comment]
Hi @Florent2 , I've sent u a pull request by adding some basic rspec tests around the app. This would be just a starting point and we can add more tests going forward. :)

This would fix the issue mentioned in #15 too.
