### ISSUE TITLE
Need to update "status" attribute in db/seeds.rb

### ISSUE THREAD

**Issue by jasnow** [rubyperu/ready4rails#15]
Need to update "status" attribute in db/seeds.rb to "status_rails4" or "status_rails5".

Also add "sqlite3" to Gemfile file.

**Comment by Florent2** [comment]
> Need to update "status" attribute in db/seeds.rb to "status_rails4" or "status_rails5".

Fixed with https://github.com/rubyperu/ready4rails/commit/4f32c6f7701010ef7b24970098190d2aa52c2b63

> Also add "sqlite3" to Gemfile file.

Done in https://github.com/rubyperu/ready4rails/commit/0ea7452f6d3ea3958b4ae07902b5cf8505585849

Thanks!

**Comment by jasnow** [comment]
Thanks
