### ISSUE TITLE
Add data for more Rails 5 gems

### ISSUE THREAD

**Issue by connorshea** [rubyperu/ready4rails#19]
There's tons of data I've been tracking here: https://gitlab.com/gitlab-org/gitlab-ce/issues/14286

**Comment by connorshea** [comment]
cc: @Florent2 if you could tell me how to update the data, I'd be happy to help out :)

**Comment by Florent2** [comment]
@connorshea 

(sorry for the delay on my response, I'm on vacations with a limited Internet access)

Great data, thanks for sharing! I manually update the website data through the Rails production console, I'll be able to do the updates with your data next week. I'll report in this issue when it's done.

**Comment by connorshea** [comment]
@Florent2 it'd be awesome if the page was generated via a YML file or something else we could contribute to, though I'm probably just bikesheddding at this point :)

**Comment by Florent2** [comment]
@connorshea thanks again for the data, I've updated http://www.ready4rails.net/ accordingly.

> it'd be awesome if the page was generated via a YML file or something else we could contribute to, though I'm probably just bikeshedding at this point :)

would be better indeed ;) a static website generated from YML or JSON files would work great, maybe http://www.ready4rails.net/gemfile_check/new could be implemented with front-end code only
